version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aman-test
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    command: npm run deploy:docker
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4003:4003
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgresql://user:password@db:5432/aman-test?schema=public'
      SECRET: 'supersecret'

volumes:
  postgres_data:
